### ISSUE TITLE
crashes after a refresh

### ISSUE THREAD

**Issue by soichih** [koopjs/koop-gist#3]
My koop instance can display GeoJson object from gist the first time I open the page, but when I refresh the page, nothing gets displayed on the map. (same issue for koop-github also)

I saw following message once, but so far I can't recreate this consistently.. I am not sure if this is related to the issue.

TypeError: Cannot read property 'geometry' of undefined
    at Object.module.exports.setGeomType (/koop/node_modules/koop-server/lib/FeatureServices.js:83:18)
    at Object.module.exports.info (/koop/node_modules/koop-server/lib/FeatureServices.js:106:19)
    at Object.exports._processFeatureServer (/koop/node_modules/koop-server/lib/Controller.js:55:27)
    at /koop/node_modules/koop-gist/controller/index.js:91:20
    at /koop/node_modules/koop-gist/models/Gist.js:36:7
    at /koop/node_modules/koop-server/lib/Cache.js:37:9
    at Statement.<anonymous> (/koop/node_modules/koop-server/lib/SQLite.js:328:13)
--> in Database#all('select * from "kooptimers" where id=\'Gist:6178185:0:timer\'', [Function])
    at Object.module.exports._query (/koop/node_modules/koop-server/lib/SQLite.js:347:13)
    at Object.module.exports.timer.get (/koop/node_modules/koop-server/lib/SQLite.js:323:14)
    at Object.exports.process (/koop/node_modules/koop-server/lib/Cache.js:34:20)
    at /koop/node_modules/koop-server/lib/Cache.js:97:10
    at Statement.<anonymous> (/koop/node_modules/koop-server/lib/SQLite.js:167:15)
Program node server.js exited with code 8

**Comment by ngoldman** [comment]
I believe this has been resolved.
